### PR TITLE
Modify WindowDelegate to own its state

### LINKED ISSUE #346: Segfault in glutin::winimpl::WindowDelegate::class::window_did_resize when using Amethyst WM
OS: OS X Yosemite 10.10.2
Hardware: MacBook Pro (Retina, 15", Late 2013)
"Window manager": Amethyst (https://github.com/ianyh/Amethyst)

The bug can be reproduced by using the minimal window example (``cargo run --example window``) on OS X while Amethyst is set to any window layout except for floating (as floating does not resize or modify window sizes or positions in any way). Resizing manually without Amethyst (or with Amethyst in floating mode) does not trigger this crash.

The line which seems to be the culprit (I have managed to use gdb to get that at least, I am not very proficient in gdb usage yet and macros makes it kinda hard for me to debug further) is https://github.com/tomaka/glutin/blob/ee2a5e4a2f020e79cfa2d34bfb82fab574a61bff/src/cocoa/mod.rs#L84

This function is only triggered once in both scenarios, but only causes a crash when Amethyst does the window resizing. And I cannot seem to be able to dump the contents of the state variable, getting an error along the lines of ``Cannot access memory at address 0x436400`` from gdb whenever I try, no matter if it is going to crash or not.

Stacktrace of crash:
```
Crashed Thread:        1  Dispatch queue: com.apple.libdispatch-manager

Exception Type:        EXC_CRASH (SIGSEGV)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Thread 0:: Dispatch queue: com.apple.main-thread
0   window                        	0x000000010efd4eda sys::stack_overflow::imp::signal_handler::h1831eab9b541d1cc3yH + 922
1   libsystem_platform.dylib      	0x00007fff9bacdf1a _sigtramp + 26
2   ???                           	000000000000000000 0 + 0
3   window                        	0x000000010efb0dc6 winimpl::WindowDelegate::class::window_did_resize::h258067217522b3a7zla + 70
4   com.apple.CoreFoundation      	0x00007fff8f371cdc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
5   com.apple.CoreFoundation      	0x00007fff8f263244 _CFXNotificationPost + 3140
6   com.apple.Foundation          	0x00007fff93b22c31 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
7   com.apple.AppKit              	0x00007fff978674bc -[NSWindow _setFrameCommon:display:stashSize:] + 2801
8   com.apple.AppKit              	0x00007fff97eb8f36 -[NSWindow(NSWindowAccessibility) accessibilitySetSizeAttribute:] + 646
9   com.apple.AppKit              	0x00007fff97c715a4 NSAccessibilityEntryPointSetValueForAttribute + 656
10  com.apple.AppKit              	0x00007fff97a9f8cf SetAttributeValue + 371
11  com.apple.HIServices          	0x00007fff9b155674 _AXXMIGSetAttributeValue + 454
12  com.apple.HIServices          	0x00007fff9b15f169 _XSetAttributeValue + 624
13  com.apple.HIServices          	0x00007fff9b13ba13 mshMIGPerform + 199
14  com.apple.CoreFoundation      	0x00007fff8f2d38f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
15  com.apple.CoreFoundation      	0x00007fff8f2d386b __CFRunLoopDoSource1 + 475
16  com.apple.CoreFoundation      	0x00007fff8f2c53e7 __CFRunLoopRun + 2375
17  com.apple.CoreFoundation      	0x00007fff8f2c4858 CFRunLoopRunSpecific + 296
18  com.apple.HIToolbox           	0x00007fff94a8baef RunCurrentEventLoopInMode + 235
19  com.apple.HIToolbox           	0x00007fff94a8b86a ReceiveNextEventCommon + 431
20  com.apple.HIToolbox           	0x00007fff94a8b6ab _BlockUntilNextEventMatchingListInModeWithFilter + 71
21  com.apple.AppKit              	0x00007fff97776f81 _DPSNextEvent + 964
22  com.apple.AppKit              	0x00007fff97776730 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
23  window                        	0x000000010efc2afc message::_$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$.MessageArguments::send::h13802515626889427100 + 236
24  window                        	0x000000010efc29f1 appkit::id.NSApplication::nextEventMatchingMask_untilDate_inMode_dequeue_::h11f4d971a7c96cffGTa + 305
25  window                        	0x000000010efb73a0 winimpl::WaitEventsIterator$LT$$u27$a$GT$.Iterator::next::he24ae6f876159b6clEa + 464
26  window                        	0x000000010efc1ca1 window::WaitEventsIterator$LT$$u27$a$GT$.Iterator::next::hcca2377f9fa5f19fnFd + 65
27  window                        	0x000000010efa638a main::haea97222d1fda9a9ere + 506
28  window                        	0x000000010efd7609 rust_try_inner + 9
29  window                        	0x000000010efd75f6 rust_try + 6
30  window                        	0x000000010efd6dff rt::lang_start::h6baf6e572388f6251fJ + 1151
31  window                        	0x000000010efa649f main + 79
32  libdyld.dylib                 	0x00007fff94d655c9 start + 1

Thread 1 Crashed:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff99874232 kevent64 + 10
1   libdispatch.dylib             	0x00007fff95fa8a6a _dispatch_mgr_thread + 52

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff9987394a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8f5eb40d start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff9987394a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8f5eb40d start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff9987394a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8f5eb40d start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff9987394a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8f5eb40d start_wqthread + 13

Thread 6:

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000004  rbx: 0x0000000000000000  rcx: 0x000000010f1065b8  rdx: 0x0000000000000000
  rdi: 0x0000000000000003  rsi: 0x0000000000000000  rbp: 0x000000010f106640  rsp: 0x000000010f1065b8
   r8: 0x0000000000000001   r9: 0x0000000000000000  r10: 0x000000010f1065d0  r11: 0x0000000000000246
  r12: 0x00007fff95fc8258  r13: 0x00007fff7ec28ec0  r14: 0x000000010f1065d0  r15: 0x000000010f106600
  rip: 0x00007fff99874232  rfl: 0x0000000000000247  cr2: 0x0000000108f78000
  
Logical CPU:     0
Error Code:      0x02000171
Trap Number:     133
```

### PR DESCRIPTION
**Pull request by SSheldon**
The `WindowDelegate` has some very important state, but it doesn't own it; a pointer to the state is just given to it before we poll for events. This flow is a little complicated and allows issues like #346 to happen, where a delegate method is called when the state isn't set.

We can modify the delegate to own it's state. This also reduces some duplication where state had to be stored on the `Window` only to be transferred to the `Delegate`.

I think this will fix #346 but I haven't installed Amethyst to reproduce it.

Tested with the examples and everything worked as expected.

### CODE REVIEW

**Comment by SSheldon** [comment]
cc @bjz, @ryanstew: any feedback on this change?

File: src/cocoa/mod.rs [hunk 1]
```diff
@@ -119,16 +118,27 @@ impl WindowDelegate {
         }
     }
 
-    fn new(window: id) -> WindowDelegate {
+    fn new(state: DelegateState) -> WindowDelegate {
+        // Box the state so we can give a pointer to it
+        let mut state = Box::new(state);
+        let state_ptr: *mut DelegateState = &mut *state;
         unsafe {
             let delegate: id = msg_send![WindowDelegate::class(), new];
```
Comment (ryanstew) [inline src/cocoa/mod.rs]: Consider wrapping in an IdRef here instead of below? I initially intended to handle all allocations this way, to protect against early-return now and in the future. Missed this one (since it uses `new` and I was only looking for `alloc`s).

File: src/cocoa/mod.rs [hunk 2]
```diff
@@ -621,7 +617,7 @@ impl Window {
     }
 
     pub fn set_window_resize_callback(&mut self, callback: Option<fn(u32, u32)>) {
-        self.resize = callback;
+        self.delegate.state.handler = callback;
```
Comment (ryanstew) [inline src/cocoa/mod.rs]: While you're poking this code, consider a more descriptive name? It took me a bit of tracing to prove to myself that `handler` is really *just* `resize_handler`.

**Comment by ryanstew** [comment]
With the caveat that I don't know the history of the old approach, this seems like an improvement to me.

**Comment by SSheldon** [comment]
Good suggestions @ryanstew, addressed. Thanks!

**Comment by tomaka** [comment]
Let's merge this!
