### PR TITLE
fix(wgl): handle unreliable WGL_TRANSPARENT_ARB by returning None

### LINKED ISSUE #1717: WGL backend supports_transparency is false
Hello!

I attempted to create a transparent window using egui, but it was not transparent. After investigating further, I discovered that the issue stems from the finalize_window (https://github.com/rust-windowing/glutin/blob/master/glutin-winit/src/lib.rs#L194) function. The supports_transparency method returns false for me. Upon additional research, it appears that the wgl_extra::TRANSPARENT_ARB attribute is consistently false on my setup, which seems odd given that I have a modern discrete GPU with up-to-date drivers. And this attribute is false on windows, compiling and running same code under  WSL ubuntu makes this attribute True.

Moreover, the Glutin window example is transparent since the finalize_window function is never called for it. I'm wondering if it's safe to remove this check entirely and proceed without it. According to the Winit code, it creates transparent windows without performing any compatibility checks. So, I'm confused about why Glutin modifies this behavior.

Could someone clarify this for me or suggest a solution?

### PR DESCRIPTION
**Pull request by ManiaciaChao**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

Fixes #1717 

### Why

`WGL_TRANSPARENT_ARB` is unreliable and can return false negatives, leading to incorrect false results.
e.g. https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/issues/29

### How

Return `None` instead of `Some(false)` when transparency can’t be determined reliably, providing consistent semantics and avoiding misleading results.

### CODE REVIEW

File: glutin/src/api/wgl/config.rs [hunk 1]
```diff
@@ -445,7 +445,12 @@ impl GlConfig for Config {
         if self.inner.descriptor.as_ref().is_some() {
             None
         } else {
-            unsafe { Some(self.raw_attribute(wgl_extra::TRANSPARENT_ARB as c_int) != 0) }
+            // WGL_TRANSPARENT_ARB is not reliable and can sometimes produce false
+            // negatives. return None to provide consistent semantics, since we
+            // don't have any better way to detect
+            let transparent =
+                unsafe { self.raw_attribute(wgl_extra::TRANSPARENT_ARB as c_int) != 0 };
+            transparent.then_some(true)
```
Comment (kchibisov) [inline glutin/src/api/wgl/config.rs]: Use `filter` and make `< 0` into None then, and then do a `map?

Comment (kchibisov) [inline glutin/src/api/wgl/config.rs]: if the goal was to make only `1` work, you should explicitly do so by using `== 1` and returning `None` otherwise.

**Review by kchibisov — CHANGES_REQUESTED** [review]

File: glutin/src/api/wgl/config.rs (hunk 1 above)
Comment (ManiaciaChao) [reply glutin/src/api/wgl/config.rs]: Good catch! I'll revise this.

**Comment by ManiaciaChao** [comment]
Looks like the CI is being blocked by issues in existing code outside of this PR.

**Review by kchibisov — APPROVED** [review]
