### PR TITLE
Fix cocoa headless. Fixes #635

### LINKED ISSUE #635: Headless rendering on OSX/Cocoa not working
Right now it gives an error `version '150' is not supported` because it's using the legacy version of OpenGL. Adding this:

```rust
NSOpenGLPFAOpenGLProfile as u32, NSOpenGLProfileVersion3_2Core as u32,
```

to https://github.com/tomaka/glutin/blob/master/src/api/cocoa/headless.rs#L39 takes it a bit further; the shaders will load and run. However I can't get it to actually render anything: the rendered image is just a blank image of whatever you put in `gl::ClearColor`, but no geometry shows up.

I've tried a bunch of variations for the `attributes` but none of them have made any difference.

I also tried switching the framebuffer code in https://github.com/tomaka/glutin/blob/master/src/api/cocoa/headless.rs#L70 to:

```rust
let mut renderbuffer: u32 = 0;
//Set up a FBO with one renderbuffer attachment
gl::GenFramebuffersEXT(1, &mut framebuffer);
gl::BindFramebufferEXT(gl::FRAMEBUFFER_EXT, framebuffer);
gl::GenRenderbuffersEXT(1, &mut renderbuffer);
gl::BindRenderbufferEXT(gl::RENDERBUFFER_EXT, renderbuffer);
gl::RenderbufferStorageEXT(gl::RENDERBUFFER_EXT, gl::RGBA8, 1024, 768);
gl::FramebufferRenderbufferEXT(gl::FRAMEBUFFER_EXT, gl::COLOR_ATTACHMENT0_EXT,
                 gl::RENDERBUFFER_EXT, renderbuffer);
let status = gl::CheckFramebufferStatusEXT(gl::FRAMEBUFFER_EXT);
if status != gl::FRAMEBUFFER_COMPLETE_EXT {
    panic!("Error while creating the framebuffer");
}
```

which I believe is closer to what is specified in https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_offscreen/opengl_offscreen.html, but it doesn't seem to make a difference.

The way I'm reading out the data is through:
```rust
e: Vec<u8> = vec![0; 1024 * 768 * 4];
gl::ReadPixels(0, 0, 1024, 768, gl::RGBA, gl::UNSIGNED_BYTE, value.as_mut_ptr() as *mut GLvoid);
let image = RgbaImage::from_raw(1024, 768, value).unwrap();
image.save(Path::new("test.png"));
```
(using the piston image library).

Any suggestions and ideas appreciated, would be really cool to get this working!

### PR DESCRIPTION
**Pull request by FredrikNoren**

### CODE REVIEW

**Comment by FredrikNoren** [comment]
Ping @tomaka

**Comment by tomaka** [comment]
Ah yeah, I usually leave PRs related to OS/X in the hope that someone review them.

File: build.rs [hunk 1]
```diff
@@ -180,8 +180,8 @@ fn main() {
 
     let mut file = File::create(&dest.join("test_gl_bindings.rs")).unwrap();
     gl_generator::generate_bindings(gl_generator::StructGenerator,
-                                    gl_generator::registry::Ns::Gles2,
+                                    gl_generator::registry::Ns::Gl,
```
Comment (tomaka) [inline build.rs]: That's not a good change. The tests are supposed to run on platforms like Android that don't support regular OpenGL. In fact I think the version `3.0` was a mistake, it should be `2.0`.

File: src/api/cocoa/headless.rs [hunk 2]
```diff
@@ -33,9 +26,14 @@ impl HeadlessContext {
...
-                NSOpenGLPFAAccelerated as u32,
-                NSOpenGLPFAAllowOfflineRenderers as u32,
                 NSOpenGLPFADoubleBuffer as u32,
+                NSOpenGLPFAClosestPolicy as u32,
+                NSOpenGLPFAColorSize as u32, 24,
+                NSOpenGLPFAAlphaSize as u32, 8,
+                NSOpenGLPFADepthSize as u32, 24,
+                NSOpenGLPFAStencilSize as u32, 8,
+
+                NSOpenGLPFAOpenGLProfile as u32, NSOpenGLProfileVersion3_2Core as u32,
```
Comment (tomaka) [inline src/api/cocoa/headless.rs]: This should be determined depending on the attributes passed to the constructor, not arbitrarily.

File: src/api/cocoa/headless.rs [hunk 3]
```diff
@@ -66,28 +61,12 @@ impl HeadlessContext {
...
-            panic!("Error while creating the framebuffer");
-        }
-
         Ok(())
     }
 
     #[inline]
     fn is_current(&self) -> bool {
-        unimplemented!()
+        true
```
Comment (tomaka) [inline src/api/cocoa/headless.rs]: I don't think that's correct

File: tests/headless.rs [hunk 4]
```diff
@@ -1,28 +1,62 @@
...
         gl.Clear(gl::COLOR_BUFFER_BIT);
+        gl.Enable(gl::SCISSOR_TEST);
+        gl.Scissor(1, 0, 1, 1);
+        gl.ClearColor(1.0, 0.0, 0.0, 1.0);
+        gl.Clear(gl::COLOR_BUFFER_BIT);
+
+        let mut values: Vec<u8> = vec![0;(width*height*4) as usize];
+        gl.ReadPixels(0, 0, width, height, gl::RGBA, gl::UNSIGNED_BYTE, values.as_mut_ptr() as *mut GLvoid);
+
+        println!("{:?}", values);
```
Comment (tomaka) [inline tests/headless.rs]: Please don't println the values.

File: build.rs (hunk 1 above)
Comment (FredrikNoren) [inline build.rs]: Yeah I wasn't sure about this one. I changed it back to GLes, but when I tried to change to 2.0 the examples stuff started breaking so left it at 3.0 (started getting error that a lot of functions weren't available like `BindVertexArray` and `BindVertexArray`, but didn't look too deeply into it).

File: src/api/cocoa/headless.rs (hunk 2 above)
Comment (FredrikNoren) [inline src/api/cocoa/headless.rs]: I pulled out the attributes construction into a helper function so that it's using the same one as the windowed.

File: src/api/cocoa/headless.rs (hunk 3 above)
Comment (FredrikNoren) [inline src/api/cocoa/headless.rs]: Yeah wasn't sure about that either, changed back.

File: tests/headless.rs (hunk 4 above)
Comment (FredrikNoren) [inline tests/headless.rs]: Whops, fixed

File: build.rs (hunk 1 above)
Comment (FredrikNoren) [inline build.rs]: For reference here's the output from the build with gles 2.0:

```
examples/support/mod.rs:47:12: 47:30 error: attempted access of field `BindVertexArray` on type `support::gl::Gles2`, but no field with that name was found
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                      ^~~~~~~~~~~~~~~~~~
examples/support/mod.rs:47:15: 47:30 help: did you mean `BindTexture`?
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                         ^~~~~~~~~~~~~~~
examples/support/mod.rs:49:16: 49:44 error: no method named `GenVertexArrays` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:49             gl.GenVertexArrays(1, &mut vao);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/support/mod.rs:50:16: 50:36 error: no method named `BindVertexArray` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:50             gl.BindVertexArray(vao);
                                          ^~~~~~~~~~~~~~~~~~~~
examples/support/mod.rs:47:12: 47:30 error: attempted access of field `BindVertexArray` on type `support::gl::Gles2`, but no field with that name was found
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                      ^~~~~~~~~~~~~~~~~~
examples/support/mod.rs:47:15: 47:30 help: did you mean `BindTexture`?
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                         ^~~~~~~~~~~~~~~
examples/support/mod.rs:49:16: 49:44 error: no method named `GenVertexArrays` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:49             gl.GenVertexArrays(1, &mut vao);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/support/mod.rs:50:16: 50:36 error: no method named `BindVertexArray` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:50             gl.BindVertexArray(vao);
                                          ^~~~~~~~~~~~~~~~~~~~
examples/support/mod.rs:47:12: 47:30 error: attempted access of field `BindVertexArray` on type `support::gl::Gles2`, but no field with that name was found
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                      ^~~~~~~~~~~~~~~~~~
examples/support/mod.rs:47:15: 47:30 help: did you mean `BindTexture`?
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                         ^~~~~~~~~~~~~~~
examples/support/mod.rs:49:16: 49:44 error: no method named `GenVertexArrays` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:49             gl.GenVertexArrays(1, &mut vao);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/support/mod.rs:50:16: 50:36 error: no method named `BindVertexArray` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:50             gl.BindVertexArray(vao);
                                          ^~~~~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Build failed, waiting for other jobs to finish...
error: aborting due to 3 previous errors
error: aborting due to 3 previous errors
examples/support/mod.rs:47:12: 47:30 error: attempted access of field `BindVertexArray` on type `support::gl::Gles2`, but no field with that name was found
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                      ^~~~~~~~~~~~~~~~~~
examples/support/mod.rs:47:15: 47:30 help: did you mean `BindTexture`?
examples/support/mod.rs:47         if gl.BindVertexArray.is_loaded() {
                                         ^~~~~~~~~~~~~~~
examples/support/mod.rs:49:16: 49:44 error: no method named `GenVertexArrays` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:49             gl.GenVertexArrays(1, &mut vao);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/support/mod.rs:50:16: 50:36 error: no method named `BindVertexArray` found for type `support::gl::Gles2` in the current scope
examples/support/mod.rs:50             gl.BindVertexArray(vao);
                                          ^~~~~~~~~~~~~~~~~~~~
```

Comment (tomaka) [inline build.rs]: Ah yeah, you're right. That's an annoying thing about OpenGL. In regular OpenGL it's mandatory to use vertex array objects, but with OpenGL ES 2.0 they don't exist. So you have to take care of this. Leave it to GLES 3.0 is fine.

**Comment by tomaka** [comment]
Thanks!
