### PR TITLE
Fixed setting cursor and cursor state

### LINKED ISSUE #355: Cursors are broken on win32
For example putting your cursor on the border of the window doesn't bring the resizing arrows.

This is probably due to the interception of `WM_SETCURSOR`.

### PR DESCRIPTION
**Pull request by regnierof**
Also fixed the broken example 'grabbing'

Closes #355

### CODE REVIEW

File: examples/grabbing.rs [hunk 1]
```diff
@@ -18,8 +18,8 @@ fn main() {
 
     let context = support::load(&window);
     let mut grabbed = false;
-    
-    for event in window.poll_events() {
+
+    for event in window.wait_events() {
```
Comment (tomaka) [inline examples/grabbing.rs]: What's the purpose of this change? Using `wait_events` means that the window won't be redrawn at each frame.

File: src/api/win32/mod.rs [hunk 2]
```diff
@@ -261,41 +265,55 @@ impl Window {
...
+            MouseCursor::EwResize | MouseCursor::ColResize => winapi::IDC_SIZEWE,
+            MouseCursor::NsResize | MouseCursor::RowResize => winapi::IDC_SIZENS,
+            MouseCursor::Wait | MouseCursor::Progress => winapi::IDC_WAIT,
+            MouseCursor::Help => winapi::IDC_HELP,
+            _ => winapi::IDC_ARROW, // use arrow for the missing cases.
+        };
+
+        unsafe {
+            let mut cur = self.window_state.lock().unwrap();
+            cur.cursor = mem::transmute(cursor_id);
```
Comment (tomaka) [inline src/api/win32/mod.rs]: Could you use the right type for `cur.cursor` and remove this transmute? (I guess `*const winapi::wchar_t`).
Transmutes are the last resort because it's very error-prone.

**Comment by tomaka** [comment]
Thanks!
It looks good other than the two small nitpicks.

File: examples/grabbing.rs (hunk 1 above)
Comment (regnierof) [inline examples/grabbing.rs]: I changed it because when I call poll_events() on my windows machine, the window disappears after being on the screen for a fraction of a second.

I thought it was a bug, so I changed it to wait_events(), which makes the window stick on the screen.

File: src/api/win32/mod.rs (hunk 2 above)
Comment (regnierof) [inline src/api/win32/mod.rs]: Ah, the transmute was a silly work around. I was supposed to change it before I sent the PR but I forgot about it.

File: examples/grabbing.rs (hunk 1 above)
Comment (tomaka) [inline examples/grabbing.rs]: Ahhh you're right. I didn't notice that there was no `loop {}` around the thing.
Yeah let's fix that with `wait_events`.
